[package]
name = "tui-2048"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
crossterm = "0.27.0"
ratatui = "0.25.0"
itertools = "0.12.0"
unicode-width = "0.1.11"
palette = "0.7.3"
rand = "0.8.5"